In [2]:
# importing required libraries
import tensorflow as tf
from tensorflow import keras
from keras.datasets import mnist
from keras.layers import Dense,Flatten,Conv2D,AveragePooling2D
from keras.models import Sequential

In [11]:
# Loading dataset and splitting train and test
(X_train,y_train),(X_test,y_test) = mnist.load_data()

In [12]:
X_train.shape

(60000, 28, 28)

In [13]:
X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [14]:
# Reshaping the image dimensions
X_train = X_train.reshape(X_train.shape[0],28,28,1)
X_test = X_test.reshape(X_test.shape[0],28,28,1)


In [15]:
X_train.shape

(60000, 28, 28, 1)

In [17]:
# Normalization # min-max scaler
X_train = X_train/255
X_test = X_test/255

In [18]:
# Before one-hot encoding
y_train[0]

5

In [19]:
# Performing one-hot encoding
y_train = keras.utils.to_categorical(y_train,10)
y_test = keras.utils.to_categorical(y_test,10)

In [20]:
# After one-hot encoding
y_train[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [21]:
# Implementing architecture
model = Sequential()

model.add(Conv2D(6,kernel_size=(5,5),activation='tanh',input_shape=(28,28,1)))
model.add(AveragePooling2D(pool_size=(2,2),strides=2))

model.add(Conv2D(16,kernel_size=(5,5),activation='tanh'))
model.add(AveragePooling2D(pool_size=(2,2),strides=2))

model.add(Flatten())

model.add(Dense(120,activation='tanh'))
model.add(Dense(84,activation='tanh'))
model.add(Dense(10,activation='softmax'))



In [22]:
# Checking the model summary
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 24, 24, 6)         156       
                                                                 
 average_pooling2d (Average  (None, 12, 12, 6)         0         
 Pooling2D)                                                      
                                                                 
 conv2d_1 (Conv2D)           (None, 8, 8, 16)          2416      
                                                                 
 average_pooling2d_1 (Avera  (None, 4, 4, 16)          0         
 gePooling2D)                                                    
                                                                 
 flatten (Flatten)           (None, 256)               0         
                                                                 
 dense (Dense)               (None, 120)               3

In [27]:
# Initializing loss,optimizer,metrics
loss = keras.metrics.categorical_crossentropy
optimizer = keras.optimizers.Adam()
metrics = ["accuracy"]

In [28]:
# Compiling the model
model.compile(loss=loss,optimizer=optimizer,metrics =metrics )

In [29]:
# Training the model
model.fit(X_train,y_train,batch_size=128,epochs=10,verbose=1,validation_data=(X_test,y_test))

Epoch 1/10
469/469 [==============================] - 8s 8ms/step - loss: 0.3549 - accuracy: 0.8979 - val_loss: 0.1858 - val_accuracy: 0.9440
Epoch 2/10
469/469 [==============================] - 3s 6ms/step - loss: 0.1313 - accuracy: 0.9605 - val_loss: 0.0983 - val_accuracy: 0.9692
Epoch 3/10
469/469 [==============================] - 3s 5ms/step - loss: 0.0868 - accuracy: 0.9736 - val_loss: 0.0757 - val_accuracy: 0.9762
Epoch 4/10
469/469 [==============================] - 3s 5ms/step - loss: 0.0646 - accuracy: 0.9802 - val_loss: 0.0634 - val_accuracy: 0.9803
Epoch 5/10
469/469 [==============================] - 3s 7ms/step - loss: 0.0527 - accuracy: 0.9832 - val_loss: 0.0608 - val_accuracy: 0.9811
Epoch 6/10
469/469 [==============================] - 3s 6ms/step - loss: 0.0424 - accuracy: 0.9870 - val_loss: 0.0523 - val_accuracy: 0.9824
Epoch 7/10
469/469 [==============================] - 3s 5ms/step - loss: 0.0367 - accuracy: 0.9884 - val_loss: 0.0511 - val_accuracy: 0.9832
Epoch 

In [30]:
score = model.evaluate(X_test,y_test)

313/313 [==============================] - 1s 3ms/step - loss: 0.0427 - accuracy: 0.9863


In [31]:
print(f"Test loss : {score[0]}")
print(f"Test accuracy : {score[1]}")


Test loss : 0.042711783200502396
Test accuracy : 0.986299991607666


In [32]:
predictions = model.predict(X_test)

313/313 [==============================] - 1s 3ms/step


In [33]:

predictions[0]

array([4.4331155e-06, 1.3408909e-06, 2.4835244e-06, 1.3618458e-04,
       6.6672715e-07, 4.2848006e-07, 1.8145624e-10, 9.9983728e-01,
       1.7071391e-06, 1.5510455e-05], dtype=float32)

In [37]:
import numpy as np

np.argmax(y_test[0])

7

In [38]:
np.argmax(predictions[0])

7